export const CHARACTER_GET = "@CHARACTER_GET";
export const CHARACTER_GET_SUCCESS = "@CHARACTER_GET_SUCCESS";
export const CHARACTER_GET_FAILURE = "@CHARACTER_GET_FAILURE";

export const CHARACTER_GET_ALL = "@CHARACTER_GET_ALL";
export const CHARACTER_GET_ALL_SUCCESS = "@CHARACTER_GET_ALL_SUCCESS";
export const CHARACTER_GET_ALL_FAILURE = "@CHARACTER_GET_ALL_FAILURE";

export const FILTER_CHARACTERS = "@FILTER_CHARACTERS";

export const LIKE_CHARACTERS = "@LIKE_CHARACTERS";
export const REMOVELIKE_CHARACTERS = "@REMOVELIKE_CHARACTERS";

export const ADD_COMIC = "@ADD_COMIC";
export const REMOVE_COMIC = "@REMOVE_COMIC";

export const TOGGLE_FAVORITE = "@TOGGLE_FAVORITE";
export const TOGGLE_SEARCH = "@TOGGLE_SEARCH"

export const CHARACTER_GET_SERACH_TERM = "@CHARACTER_GET_SERACH_TERM";
export const RESET_SEARCH = "@RESET_SEARCH";
export const CHARACTER_GET_SERACH_TERM_SUCCESS = "@CHARACTER_GET_SERACH_TERM_SUCCESS";
export const CHARACTER_GET_SERACH_TERM_FAILURE = "@CHARACTER_GET_SERACH_TERM_FAILURE";
export const ITEMVISIT_SEARCH = "@ITEMVISIT_SEARCH";

export const CHARACTER_GET_COMIC = "@CHARACTER_GET_COMIC";
export const CHARACTER_GET_COMIC_SUCCESS = "@CHARACTER_GET_COMIC_SUCCESS";
export const CHARACTER_GET_COMICFAILURE = "@CHARACTER_GET_COMICFAILURE";

// eslint-disable-next-line
export default {
  CHARACTER_GET,
  CHARACTER_GET_SUCCESS,
  CHARACTER_GET_FAILURE,
  CHARACTER_GET_ALL,
  CHARACTER_GET_ALL_SUCCESS,
  CHARACTER_GET_ALL_FAILURE,
  FILTER_CHARACTERS,
  ADD_COMIC,
  REMOVE_COMIC,
  LIKE_CHARACTERS,
  REMOVELIKE_CHARACTERS,
  TOGGLE_FAVORITE,
  TOGGLE_SEARCH,
  CHARACTER_GET_SERACH_TERM,
  CHARACTER_GET_SERACH_TERM_SUCCESS,
  CHARACTER_GET_SERACH_TERM_FAILURE,
  ITEMVISIT_SEARCH,
  RESET_SEARCH,
  CHARACTER_GET_COMIC,
  CHARACTER_GET_COMIC_SUCCESS,
  CHARACTER_GET_COMICFAILURE
};
